export type ButtonFillType = 'solid' | 'outline' | 'clear';
export type ButtonShapeType = 'round' | 'default' | 'circle' | 'custom';
export type ButtonSizeType = 'small' | 'default' | 'large';
export type ButtonColorType = 'danger' | 'warning' | 'primary' | 'secondary' | 'success' | 'dark' | 'light' | 'grey';
export type TIconNames =
  | 'add-capsule-blue-svg'
  | 'add-capsule-grey-svg'
  | 'add-capsule-white-svg'
  | 'add-record_hover-svg'
  | 'add-record-svg'
  | 'alert-svg'
  | 'approved-svg'
  | 'calendar-svg'
  | 'caret-inverted-svg'
  | 'caret-left-svg'
  | 'caret-svg'
  | 'checked-svg'
  | 'close_blue_active-svg'
  | 'close_white_active-svg'
  | 'close_white-svg'
  | 'close-active-svg'
  | 'close-grey-svg'
  | 'close-white-svg'
  | 'close-svg'
  | 'edit-png'
  | 'excel-blue-svg'
  | 'excel-svg'
  | 'green-smile-svg'
  | 'hamburger-menu_hover-svg'
  | 'hamburger-menu-svg'
  | 'info-svg'
  | 'internal_computer-svg'
  | 'internal_grey_exclamation-svg'
  | 'internal_greyexclamation1-svg'
  | 'maximise_blue-svg'
  | 'maximise_dark_blue-svg'
  | 'minimise_blue-svg'
  | 'minimise_dark_blue-svg'
  | 'new-window-svg'
  | 'orange-smile-svg'
  | 'red-smile-svg'
  | 'search-svg'
  | 'sortupdown-svg'
  | 'svg-info-svg'
  | 'svg-sortupdown-svg'
  | 'svg-whitearrow-svg'
  | 'svg-whitex-svg'
  | 'tabs_checked-png'
  | 'tick-svg'
  | 'warning-red-svg'
  | 'warning-png'
  | 'whitearrow-svg'
  | 'whitex-svg'
  | 'x-blue-svg'
  | 'x-hover-svg';
